<?php


use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\Request;
use Drupal\Core\Session\AccountInterface;
use Drupal\user\UserInterface;


/**
* @file
* Redirects.
*/
#session_start();
#module_set_weight('referrer_gatekeep', 100000);


\Drupal::service('page_cache_kill_switch')->trigger();



function debug_to_console($data) {
  $output = $data;
  if (is_array($output))
    $output = implode(',', $output);

  echo "<script>console.log('Debug Objects: " . $output . "' );</script>";

}


#::getSubscribedEvents();

#$events['kernel.request'][] = ['onRequest', 0];

