<?php


use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\Request;
/**
* @file
* Redirects.
*/



 function debug_to_console($data) {
   $output = $data;
   if (is_array($output))
     $output = implode(',', $output);

   echo "<script>console.log('Debug Objects: " . $output . "' );</script>";
 }

function redirect_ref() {
    $referer = \Drupal::state()->get('ref');
    $ref_message = \Drupal::state()->get('ref_message');
    $our_url= "{$_SERVER['HTTP_HOST']}";
    $orig = $_SERVER['HTTP_REFERER'];
    debug_to_console($referer);
    debug_to_console($orig);
    if ( !str_contains($orig, $our_url)  && $orig!=$referer ){
      echo "<script type='text/javascript'>alert('$ref_message');</script>";
      #header("Location: $referer");
      die();
    }


}

redirect_ref();
